- name: Provision Hetzner resources
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - secrets.enc

  tasks:
    - name: Register SSH key
      hcloud_ssh_key:
        api_token: "{{ hcloud_token }}"
        name: admin_ssh_key
        public_key: "{{ deploy_ssh_public_key }}"
      register: ssh_key

    - name: Setup firewall
      hetzner.hcloud.firewall:
        api_token: "{{ hcloud_token }}"
        name: firewall
        rules:
          - description: allow SSH from anywhere
            direction: in
            protocol: tcp
            source_ips:
              - 0.0.0.0/0
              - ::/0
            port: 22
          - description: allow HTTP for Let's Encrypt validation and HTTP->HTTPS redirects
            direction: in
            protocol: tcp
            source_ips:
              - 0.0.0.0/0
              - ::/0
            port: 80
          - description: allow HTTPS from anywhere
            direction: in
            protocol: tcp
            source_ips:
              - 0.0.0.0/0
              - ::/0
            port: 443
        state: present

    - name: Create server
      register: server
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        firewalls:
        - firewall
        name: server
        server_type: cx23
        image: ubuntu-26.04
        location: fsn1
        state: present
        ssh_keys:
          - "{{ ssh_key.hcloud_ssh_key.id }}"

    - ansible.builtin.debug:
        var: server.hcloud_server.ipv4_address

    - name: Write server private SSH key to temporary file
      copy:
        dest: "/tmp/server_priv_key"
        mode: "0600"
        content: "{{ deploy_ssh_private_key }}"

    - name: Add new server to in-memory inventory
      add_host:
        name: "{{ server.hcloud_server.ipv4_address }}"
        ansible_ssh_private_key_file: "/tmp/server_priv_key"
        groups: remote_servers
        ansible_user: root

- name: Hardening system
  hosts: remote_servers
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Wait for SSH connection to be available
    ansible.builtin.wait_for_connection:

  - name: Install utilities
    ansible.builtin.apt:
      pkg:
      - fail2ban
      - unattended-upgrades
      update_cache: yes

- name: Install database
  hosts: remote_servers
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    postgresql_config_dir: /etc/postgresql/18/main
  vars_files:
    - secrets.enc
  tasks:
  - name: Install PostgreSQL
    ansible.builtin.apt:
      pkg:
        - libpq-dev
        - postgresql
        - python3-psycopg2

  - name: Accept connections from anywhere
    ansible.builtin.lineinfile:
      path: "{{ postgresql_config_dir }}/postgresql.conf"
      regexp: "^listen_addresses="
      line: "listen_addresses='*'"

  - name: Grant Docker containers access to host PostgreSQL cluster
    community.postgresql.postgresql_pg_hba:
      dest: "{{ postgresql_config_dir }}/pg_hba.conf"
      contype: host
      source: 172.17.0.0/24
      method: "scram-sha-256"
      create: true

  - name: Restart PostgreSQL to pick up configuration
    ansible.builtin.systemd_service:
      name: postgresql.service
      state: restarted

  - name: Create user
    community.postgresql.postgresql_user:
      login_db: postgres
      name: "{{ postgres_user }}"
      password: "{{ postgres_password }}"
    become: true
    become_user: postgres

  - name: Create database
    community.postgresql.postgresql_db:
      name: "{{ postgres_database }}"
      owner: "{{ postgres_user }}"
    become: true
    become_user: postgres
