service: heka

image: frerich/heka

servers:
  web:
    - 178.105.198.6

proxy:
  ssl: true
  host: static.6.198.105.178.clients.your-server.de
  app_port: 4000
  healthcheck:
    path: /health

ssh:
  keys_only: true
  key_data:
    - DEPLOY_PRIVATE_SSH_KEY

registry:
  server: localhost:5555

builder:
  arch: amd64
  cache:
    type: gha

env:
  clear:
    DATABASE_URL: postgres://localhost/dummy
    PHX_HOST: static.6.198.105.178.clients.your-server.de

  secret:
    - SECRET_KEY_BASE
