service: heka

image: frerich/heka

servers:
  web:
    hosts:
    - 159.69.181.205
    options:
      "add-host": host.docker.internal:host-gateway

proxy:
  ssl: true
  host: heka.idkfa.site
  app_port: 4000
  healthcheck:
    path: /health

ssh:
  user: deploy
  keys_only: true
  key_data:
    - DEPLOY_PRIVATE_SSH_KEY

registry:
  server: localhost:5555

builder:
  arch: amd64
  cache:
    type: gha

env:
  clear:
    PHX_HOST: heka.idkfa.site
  secret:
    - DATABASE_URL
    - SECRET_KEY_BASE

aliases:
  remote: app exec -q -p -i --reuse "/app/bin/heka remote"
  psql: server exec -q -p -i "psql -h localhost -U heka -d heka"
