service: heka

image: frerich/heka

servers:
  web:
    - 178.105.198.6

accessories:
  postgres:
    image: postgres:18
    host: 178.105.198.6
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DATABASE
    directories:
      - data:/var/lib/postgresql

proxy:
  ssl: true
  host: static.6.198.105.178.clients.your-server.de
  app_port: 4000
  healthcheck:
    path: /health

ssh:
  keys_only: true
  key_data:
    - DEPLOY_PRIVATE_SSH_KEY

registry:
  server: localhost:5555

builder:
  arch: amd64
  cache:
    type: gha

env:
  clear:
    PHX_HOST: static.6.198.105.178.clients.your-server.de
  secret:
    - DATABASE_URL
    - SECRET_KEY_BASE

aliases:
  bash: app exec -q -p -i --reuse bash
  remote: app exec -q -p -i --reuse "/app/bin/heka remote"

